name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 支持手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # 安装 dos2unix
    - name: Install dos2unix
      run: sudo apt-get update && sudo apt-get install dos2unix

    # 将 gradlew 文件转换为 Unix 格式
    - name: Convert gradlew to Unix format
      run: dos2unix gradlew

    # 赋予 gradlew 文件执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
